@url=http://192.168.56.1:3000/cliente
@id=1

GET {{url}}

###
POST {{url}}
Content-Type: application/json

{
    "nombre":"Tony",
    "edad": 21
}

###
PUT {{url}}/{{id}}
Content-Type: application/json

{
    "nombre":"Anthony Cepeda",
    "edad": 31
}

###
DELETE {{url}}/{{id}}

###
GET {{url}}?nombre_like=I