"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const interfaces_1 = require("./interfaces");
const interfaces_2 = require("./interfaces");
const interfaces_3 = require("./interfaces");
const int2_1 = require("./int2");
console.log(interfaces_1.default);
console.log(interfaces_2.default);
console.log(interfaces_3.default);
console.log((0, int2_1.default)(5, 14));
const array_1 = require("./array");
for (let valor of array_1.animales)
    console.log(valor);
console.log(array_1.animales2);
console.log(array_1.aviones);
let suma = (op1, op2) => { return op1 + op2; };
console.log(suma(14, 50));
let product = (op3, op4) => { return op3 * op4; };
console.log(product(9, 14));
let concat = (p1, p2) => { return p1 + " " + p2; };
console.log(concat('Néstor', 'Costa'));
let fun = (s1) => { return s1; };
console.log(fun("Hola Mundo"));
let valor = 12;
let planti = `Esto es una plantilla con el valor ${valor}`;
console.log(planti);
let val2 = 'HOLA';
let planti2 = `${val2},esto es una saluda amistoso`;
console.log(planti2);
